### ISSUE TITLE
Icon color with tailwind classes

### ISSUE THREAD

**Issue by marifdev** [impulse/react-native-heroicons#19]
Hi,
Thanks for this great work.

I am wondering if it is possible to colorize icons using tailwind classes. For example
`<AdjustmentsHorizontalIcon className={"stroke-red-800"} />`
is not working as I can see. Is there any plan to support this?

Thank you

**Comment by ecklf** [comment]
Out of scope for this package, but I can recommend you to use something like https://github.com/vadimdemedes/tailwind-rn for styling with utility classes in React Native.
