### ISSUE TITLE
Support for solid icons

### ISSUE THREAD

**Issue by corderop** [impulse/react-native-heroicons#5]
Hi! First, thanks for working on this, you save me a lot of time!.

I've opened this issue to know if it's expected to support solid icons or there is already any way to use it. 

I could help with this in the future, but not right now (I'm too busy)

**Comment by impulse** [comment]
Already supported. Solid icons are the ones not suffixed with `Outline`

**Comment by corderop** [comment]
My fault, it was a confusion between stroke and fill
